### ISSUE TITLE
V8: running the sample fails

### ISSUE THREAD

**Issue by ktrzeciaknubisa** [jxcore/jxcore-addon#1]
Building and running the sample against JXcore SM build works ok. 

However for V8 (the latest build from jxcore master) `jx test.js` generates this output:

``` bash
dyld: lazy symbol binding failed: Symbol not found: __ZN5MozJS5Value17SetStaticFunctionEPKcPFbP9JSContextjPN2JS5ValueEEt
  Referenced from: /Users/nubisa_krzs/Documents/temp/_obastemur/jxcore-addon/build/Release/binding.node
  Expected in: dynamic lookup

dyld: Symbol not found: __ZN5MozJS5Value17SetStaticFunctionEPKcPFbP9JSContextjPN2JS5ValueEEt
  Referenced from: /Users/nubisa_krzs/Documents/temp/_obastemur/jxcore-addon/build/Release/binding.node
  Expected in: dynamic lookup

Trace/BPT trap: 5
```

**Comment by ktrzeciaknubisa** [comment]
I've found the reason. I was naive to think, that I can have use few jx binaries (`jxsm` + `jxv8`) and use them like `jxv8 install`, while I also had `jx` available (this was SM build). Thus addon was compiled against SM, not V8 as I thought.

**Comment by saper** [comment]
Maybe it would be better not to provide `NODE_MODULE_VERSION` when not building with V8? Binary modules tend to think this is `node 0.10` with the appropriate V8 version.
