### ISSUE TITLE
Building jxcore-addon on Windows fails with unresolved external symbol errors

### ISSUE THREAD

**Issue by csapoadam** [jxcore/jxcore-addon#4]
I am having problems with the basic example given here ( https://github.com/jxcore/jxcore-addon ) on Windows 7. I download the precompiled jx binary and put it on the path, then I extract the addon-master folder, and run 'jx install' inside it. Regardless of whether I try using the jx executable built for SpiderMonkey or V8, I get the linker errors. In the case of SM, the linker is missing 27 symbols, while in the case of V8, 20 symbols.

Here is an example:

![scr](https://cloud.githubusercontent.com/assets/3015877/8280529/683ba9b6-18de-11e5-9975-76fa3d3e3efa.png)

I have tried adding jx.lib to the path, as well as to the same folder with the addon sources, with no success.

**Comment by ktrzeciaknubisa** [comment]
Ok, so that's the output for SM, right? Now I receive that too.
Which is the output for V8? (it runs ok for me).

Can you also remind:
- is this Windows 64 or 32?
- which Visual Studio version?

**Comment by csapoadam** [comment]
Yes, that one was for SM. Here is a screenshot for V8:

![scr2](https://cloud.githubusercontent.com/assets/3015877/8281021/06b013fc-18e4-11e5-88f6-7460b5ba81fa.png)

I am using a 32-bit Windows and Visual Studio 2012.

**Comment by csapoadam** [comment]
Hi @ktrzeciaknubisa, do you have any updates on this. If I am correct you were able to reproduce this problem, at least for SM?

Thanks!

**Comment by obastemur** [comment]
@csapoadam Can you please try it after removing USER/.jx and USER/.node-gyp folders ?

**Comment by csapoadam** [comment]
Hi @obastemur , after removing those folders and calling 'jx install' once again, I have the following results:
- for v8, the example compiles and links. However, when I try running 'var binding = require('./build/Release/binding');' to use the generated library, I have further problems:

![error_v8](https://cloud.githubusercontent.com/assets/3015877/8391299/fab97226-1cbe-11e5-8388-051e446a764c.png)

The message means something like "the given operation cannot be found". Again, the test.js file contains just one line which tries to import the library. Inside ./build/Release/ I have the binding.exp, binding.lib, binding.node and binding.pdb files, as well as an 'obj' subdirectory.
Anyway, this is progress because the former linking error disappeared.
- for SM, the linking error also disappeared, but I can't tell whether it's actually solved because now it seems I am getting a compiler error before the linker runs:

![error_sm](https://cloud.githubusercontent.com/assets/3015877/8391325/780bc7a6-1cbf-11e5-937c-ffe0f6500e6e.png)

It seems that there is some problem with exporting that variable into the dll.

Let me know when I can try again. Thanks!

**Comment by csapoadam** [comment]
PS. In the SM case if I just remove the JXCORE_PUBLIC from that line in the .h file (leaving just "JSContext *ctx_", I receive the same linker errors.

I guess it would be important to export that member to the dll, or the problem is somewhere else.

**Comment by obastemur** [comment]
@csapoadam Latest commit makes it private hence it should not be an issue anymore.

**Comment by csapoadam** [comment]
Unfortunately for SM I am still getting:

c:\users\adam.node-gyp\jxb303\src\jx\proxy\Mozilla/JXString.h(57): error C2071
: 'jxcore::JXString::ctx_' : illegal storage class [C:\Users\Adam\Desktop\test\
build\binding.vcxproj]

I checked the file and I don't see a difference. Lines 56 and 57 still are:
  // MOZJS Specific
  JXCORE_PUBLIC JSContext *ctx_;

so then I checked on github and I see that the file JXString.h is changed there ( https://github.com/jxcore/jxcore/blob/master/src/jx/Proxy/Mozilla/JXString.h ). For some reason, when I run jx install, the file downloaded into HOME/.node-gyp is still the old one.

So, having noted that I tried moving the above two lines into the private part of the class, and removing JXCORE_PUBLIC from the beginning. However, when I do that I'm back to square 1 with the linker errors

![errrorstill](https://cloud.githubusercontent.com/assets/3015877/8392495/4a423e4e-1ced-11e5-8c64-b51da33acbee.png)

... and for the V8 version, I still cannot run the example due to that problem with process._dlopen().

**Comment by csapoadam** [comment]
PS. I have tried recompiling the jx executable as well, but it doesn't help, unfortunately, I am still unable to compile the example because of the illegal storage class for ctx_.

**Comment by csapoadam** [comment]
Hi, do you have any news on this?

**Comment by obastemur** [comment]
@csapoadam I think it's okay for V8 builds now. i.e. [leveldown-mobile](https://github.com/level/leveldown-mobile) uses same macro and compiles under Windows. However we need to separate SM libs from v8 inside node-gyp. I've opened an issue [here](https://github.com/jxcore/jxcore/issues/417) and working on it. 

I will try to handle it by tomorrow.

**Comment by csapoadam** [comment]
Thanks for your work on this.

Yes the V8 version compiles, although I am still getting the error with process._dlopen (the specified procedure could not be found) when requiring the addon. This is probably a different issue, and if it leads too far I can open a new issue.

In the meantime, thanks for working on the SM version. Let me know when I can test it.

**Comment by obastemur** [comment]
This issue should be fixed now. In order to try you need to compile jxcore/master and use it for 'jx install'

Thanks for all the details.

PS. dlopen issue might be from leveldown-mobile, it doesn't have NODE_MODULE registration like the one inside the `binding.cc` (this project)

**Comment by csapoadam** [comment]
Hi @obastemur , yes, I confirm that the addon now compiles with the SpiderMonkey version as well, and it runs, too, without the problem with dlopen. Thank you both for your help.

I'm not sure I understand what it means that the dlopen issue was from leveldown-mobile, and what I could do to fix it (for the v8 version). Or were you able to fix that?

Unfortunately I have one more issue. Maybe the solution is simple. I am now able to run my addons through jx. I am also able to import scripts from embedded applications. But I am unable to import addons from embedded applications, because I get an invalid memory access error. For example, if I have a .js file that has:

var binding = require('./build/Release/binding');
console.log("1 + 2 = " + binding.sum(1,2));

where binding is the addon I created... then I have the desired result. But if in C++, I do:

std::stringstream ss;
ss << "console.log(\"Adding 1 and 2 together \"); \n";
ss << "var binding0 = process.requireGlobal('./build/Release/testadd'); \n";
ss << "var binding1 = process.requireGlobal('./build/Release/binding'); \n";
ss << "console.log(binding1.sum(1,2)); \n";
JX_Evaluate(ss.str().c_str(), "myscript", &result);

the code will run properly until the third line (fourth line in this code) that requires binding. The testadd.js script, for example, runs perfectly. At the third line, I get:

Error: invalid access to memory location
c:\users\adam\desktop\development\maxwhere-tests\build\release\binding.node (nat
ive:jxcore_js_object 3:11)
    at  (native:jxcore_js_object:3:12)
    at process.dlopen (node.js:638:17)
    at Module.prototype.load (module.js:347:7)
    at Module._load (module.js:314:5)
    at Module.prototype.require (module.js:379:10)
    at require (module.js:397:12)
    at myscript:3:16

Do you know what causes this? Again, requiring the addon through a script run by the jx executable works fine. It is only combining the addon with an embedded application that results in problems.

Thanks again.

**Comment by obastemur** [comment]
When you call `Evaluate` from native land, it's not wrapped with the 'node's require'. What do you want is to execute a script embedded into C,C++ part of the project right?

**Comment by obastemur** [comment]
Closing this issue. Let's discuss the additional issues under a new title. Thanks!

**Comment by csapoadam** [comment]
Thanks. I created the new issue.
